AWSTemplateFormatVersion: '2010-09-09'
Description: 'Elastic Beanstalk environment with Docker image'
Resources:
  MyElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      Description: 'My Elastic Beanstalk application'
      ApplicationName: 'MyEBApplication'
  MyElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      Description: 'My Elastic Beanstalk environment for Docker image'
      EnvironmentName: 'MyEBEnvironment'
      ApplicationName: !Ref MyElasticBeanstalkApplication
      SolutionStackName: '64bit Amazon Linux 2 v3.5.6 running Docker'
      OptionSettings:
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: 'EnvironmentType'
          Value: 'SingleInstance'
        - Namespace: 'aws:elasticbeanstalk:container:MyEBApplication'
          OptionName: 'ContainerConfig'
          Value: '{"Image": "twitterscraper:latest"}'
