AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create EC2 instance and run Docker container'
Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: ami-0c94855ba95c71c99
      KeyName: my-key-pair
      SecurityGroupIds:
        - !Ref 'AWS::NoValue'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Installing Docker..."
          sudo yum update -y
          sudo amazon-linux-extras install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          echo "Starting Docker container..."
          sudo docker run -p 80:80 adsieg01/twitter-scraper:latest
