AWSTemplateFormatVersion: '2010-09-09'
Description: 'Elastic Beanstalk environment with Docker for Python app'
Resources:
  MyElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      Description: 'Twitter Scraper APP'
      ApplicationName: 'TwitterScraperApp'
  MyElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      Description: 'My Elastic Beanstalk environment for Python app'
      EnvironmentName: 'MyEBEnvironment'
      ApplicationName: !Ref MyElasticBeanstalkApplication
      SolutionStackName: '64bit Amazon Linux 2 v3.5.6 running Docker'
      OptionSettings:
        - Namespace: 'aws:elasticbeanstalk:container:docker'
          OptionName: 'Image'
          Value: 'adsieg01/twitter-scraper:latest'
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: 'EnvironmentType'
          Value: 'SingleInstance'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Elastic Beanstalk configuration"
        Parameters:
          - Image
    ParameterLabels:
      Image:
        default: "Docker image"
  AWS::CloudFormation::Init:
    config:
      files:
        "/tmp/eb_env.yaml":
          content: !Sub |
            option_settings:
              - namespace: aws:elasticbeanstalk:container:docker
                option_name: Image
                value: !Ref Image
      commands:
        01_create_eb_env:
          command: |
            /opt/elasticbeanstalk/bin/eb create ${EnvName} \
            --elb-type application \
            --region ${AWS::Region} \
            --platform "Docker 20.10.8 on 64bit Amazon Linux 2"
