version: '3'

services:
  app:
    image: adsieg01/twitter-scraper:latest
    ports:
      - "80:80"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
