name: Twitter Scraper Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        
    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy --stack-name twitter-scraper --template-file cloudformation.yaml --debug
        
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        pytest
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: adsieg01/twitter-scraper:latest
