name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        pytest
        
    - name: Deploy
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: username/repo:latest
